### PR TITLE
feat(global): :sparkles: fix minHeight & margin in AccordionSummary &…

### LINKED ISSUE #167: enhancement: Need to fix Accordion Summary & Toolbox Height Issues
#### **Describe the Bug**  
- The **toolbox** does not take the full height as expected.  
- In **AccordionSummary**, the default `minHeight` is **48px**, which is unnecessary.  
- The **default margin of 12px** on `.MuiAccordionSummary-content` is not required and should be removed.  

#### **To Reproduce**  
Steps to reproduce the issue:  
1. Go to **http://localhost:3000/appBuilder**  
2. Observe the incorrect height of the toolbox and unwanted margins in `AccordionSummary`.  

#### **Expected Behavior**  
- The **toolbox should take full height** of its container.  
- `AccordionSummary` should **not have a forced min-height of 48px**.  
- The `.MuiAccordionSummary-content` should **not have the default 12px margin, it should be less**.  

#### **Environment Details**  
**Desktop:**  
- **OS:** [Windows 11]  
- **Browser:** [Chrome]  
- **Version:** [Version 133.0.6943.98 (Official Build) (64-bit)]

### PR DESCRIPTION
**Pull request by PritamBag**
## Description
- Removed 48px minHeight from AccordionSummary.
- Eliminated default 12px margin in.MuiAccordionSummary-content.
- Ensured toolbox takes full height.

## Related Issues
Ref #167

## Checklist

- [x] I have performed a thorough self-review of my code.
- [ ] I have added or updated relevant tests for my changes.
- [ ] My code follows the project's style guidelines and best practices.
- [ ] I have updated the documentation if necessary.
- [ ] I have added or updated relevant comments in my code.
- [ ] I have resolved any merge conflicts of my branch.

## Reviewers

---

## Maintainer Notes

- [ ] Has this change been tested in a staging environment?
- [ ] Does this change introduce any breaking changes or deprecations?

### CODE REVIEW

**Review by anantakumarghosh — DISMISSED** [review]

File: package/nativeComponents/surfaces/NativeToolBox.js
Comment (anantakumarghosh) [inline package/nativeComponents/surfaces/NativeToolBox.js:1]: fix component file name

File: package/styledComponents/surfaces/SCToolBox.js
Comment (anantakumarghosh) [inline package/styledComponents/surfaces/SCToolBox.js:1]: fix component file name

File: package/index.js [hunk 1]
```diff
@@ -154,7 +154,7 @@ import NativeFooter from "./nativeComponents/surfaces/NativeFooter";
 import NativePaper from "./nativeComponents/surfaces/NativePaper";
 import NativeRightDrawer from "./nativeComponents/surfaces/NativeRightDrawer";
 import NativeToolbar from "./nativeComponents/surfaces/NativeToolbar";
-import NativeToolBox from "./nativeComponents/surfaces/NativeToolBox.js";
+import NativeToolbox from "./nativeComponents/surfaces/NativeToolbox";
```
Comment (anantakumarghosh) [inline package/index.js:157]: check filename

File: package/nativeComponents/surfaces/NativeToolBox.js
Comment (anantakumarghosh) [reply package/nativeComponents/surfaces/NativeToolBox.js:1]: resolved

File: package/styledComponents/surfaces/SCToolBox.js
Comment (anantakumarghosh) [reply package/styledComponents/surfaces/SCToolBox.js:1]: resolved

File: package/index.js (hunk 1 above)
Comment (anantakumarghosh) [reply package/index.js:157]: resolved

**Review by anantakumarghosh — APPROVED** [review]
